services:
  main:
    image: eyehol3/webpage-setup
    volumes:
      # - /var/run/docker.sock:/var/run/docker.sock
      - ./serve:/serve
  nginx:
    image: nginx
    volumes:
      - ./serve:/usr/share/nginx/html
    ports:
      - "8080:80"
    depends_on:
      - main

      