# frozen_string_literal: true

source "https://rubygems.org"
gemspec


group :jekyll_plugins do
    gem 'jekyll'
    gem "jekyll-seo-tag"
    # gem "jekyll-paginate-v2"
    # gem "jekyll-assets"
end

